### ISSUE TITLE
Redis doesn't work with hostname

### ISSUE THREAD

**Issue by mayorova** [3scale/apicast-xc#12]
## Problem
The current release relies on [apicast:v3.0.0-alpha2](https://github.com/3scale/apicast-xc/blob/master/Dockerfile-apicast#L3). However, in this release the nginx `resolver` directive was [removed](https://github.com/3scale/apicast/blob/master/CHANGELOG.md#removed-2), and APIcast built-in resolver has to be used for all connections.

apicast-xc module doesn't take this into account, so as a result, Redis connection will only be created successfully when IP address is used in `XC_REDIS_HOST`. If hostname is used, it will fail. The client will only see a `403` error, and the reason returned by the Redis library is `no resolver defined to resolve "<redis hostname>"`.

## What is needed
Redis pool used by apicast-xc should use APIcast built-in resolver for Redis hostname.

**Comment by mayorova** [comment]
Current version of apicast has some extra utilities to support Redis Auth and db selection:
https://github.com/3scale/apicast/blob/85e9f19212dca971bc50a4064d8bceece8b0222d/apicast/src/threescale_utils.lua#L98-L165

Maybe this can be used in Redis pool? Even maybe reuse `REDIS_URL` env var, and use it both in apicast and apicast-xc (maybe with a different db)?

I would even suggest to extract all Redis utilities to a separate module, and make them more reusable.

**Comment by davidor** [comment]
Thanks for reporting this @mayorova . For reference, this is the PR that introduced the breaking change in apicast: https://github.com/3scale/apicast/pull/237
